name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Hello-World-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    secret_ids:
     - ptl/azure-devops/hello-world-env-internal-dev/API_KEY
    enable_monitoring: true
    apigee_deployments:
      - environment: internal-dev
        make_spec_visible: true
        post_deploy:
          - template: templates/tests.yml
            parameters:
              service_name: ${{ variables.service_name }}
        jinja_templates:
            REQUIRE_ASID: false
      - environment: internal-dev-sandbox
        make_spec_visible: true
        jinja_templates:
            REQUIRE_ASID: false
      - environment: internal-qa-sandbox
        make_spec_visible: true
        jinja_templates:
            REQUIRE_ASID: false
      - environment: sandbox
        make_spec_visible: true
        depends_on:
          - internal_dev
          - internal_dev_sandbox
          - internal_qa_sandbox
        jinja_templates:
            REQUIRE_ASID: false