variables:
  service_name: hello-world
  short_service_name: hw
  service_base_path: hello-world
  product_display_name: Hello World
  product_description: Placeholder description
  spec_file: hello-world.json
