version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.12.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
- package-ecosystem: npm
  directory: "/sandbox"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: gitpython
    versions:
    - 3.1.13
  - dependency-name: locust
    versions:
    - 1.4.3
  - dependency-name: pip-licenses
    versions:
    - 3.3.0
