# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Hello World API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"

info:
  version: "0.0.1"
  title: Hello World API
  description: |
    ## Overview
    Use this API alongside our [tutorials](https://digital.nhs.uk/developer/tutorials).
    You can learn to connect via:
      * open-access
      * application-restricted.
      * user-restricted.


    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis). And is available via the Internet, and over the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    ## Authorisation
    This API showcases three differently authorised endpoints, [Open-access](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#open-access-apis), [Application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis) and [User-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).
      * Open-access requires no authorisation.
      * Application-restricted requires an API key presented in the 'apikey' header along with the request.
      * User-restricted requires OAuth 2.0 authorisation. This involves an OAuth 2.0 Access Token presented in the 'Authorization' header along with the request.

    ## Environments and Testing
    You can test this API using our sandbox environment:
      - `https://sandbox.api.service.nhs.uk/hello/`

    For more details on sandbox testing, see [Sandbox Testing](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing), or to try out the sandbox using our "Try this API" feature.
    Alternatively, you can try out the sandbox using our Postman collection:
    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/426d37cb9cfe17b8b96d)
      

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    - `GET /hello/world` - an example of an open-access endpoint
    - `GET /hello/application` - an example of an application-restricted endpoint
    - `GET /hello/user` - an example of a user-restricted endpoint
  contact:
    name: API Management Support
    email: api.management@nhs.net

servers:
  - url: 'https://sandbox.api.service.nhs.uk/hello-world-master'
    description: Sandbox environment.

paths:

  /hello/world:
    get:
      summary: Say hello world.
      operationId: getHello
      description: |
        Get a "Hello world!" response from an open-access endpoint.

        Use this API alongside our [open-access REST API tutorial](https://digital.nhs.uk/developer/tutorials/open-access-rest-api-tutorial) to learn how to connect to our APIs.
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello world!"
              example:
                message: "Hello world!"
      tags:
        - hello

  /hello/application:
    get:
      summary: Say hello application.
      operationId: getHelloApiKey
      description: |
        Get a "Hello application!" response from an application-restricted endpoint.

        Use this API alongside our [application-restricted REST API tutorial](https://digital.nhs.uk/developer/tutorials/application-restricted-rest-api-tutorial) to learn how to connect to our APIs.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello application!"
              example:
                message: "Hello application!"
        '401':
          description: Missing or invalid API Key
          content: 
            application/json:
              example:
                message: "Invalid ApiKey"
      security:
        - api_key: []
      tags:
        - hello

  /hello/user:
    get:
      summary: Say hello user.
      operationId: getHelloToken
      description: |
        Get a "Hello user!" response from a user-restricted endpoint.

        Use this API alongside our [user-restricted REST API tutorial](https://digital.nhs.uk/developer/tutorials/user-restricted-rest-api-tutorial) to learn how to connect to our APIs.

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello user!"
              example:
                message: "Hello user!"
        '401':
          description: Missing or invalid OAuth 2.0 Access Token
          content: 
            application/json:
              example:
                message: "Invalid access token"
      security:
        - oAuth2AuthCode: []
      tags:
        - hello

  /_status:
    get:
      summary: Health check endpoint.
      operationId: getStatus
      description: |
        Returns an empty json response. This can be used to perform service healthcheck.

        Use this API alongside our [open-access REST API tutorial](https://digital.nhs.uk/developer/tutorials/open-access-rest-api-tutorial) to learn how to connect to our APIs.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
      tags:
        - hello
components:

  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: header

    oAuth2AuthCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sandbox.api.service.nhs.uk/oauth2/authorize
          tokenUrl: https://sandbox.api.service.nhs.uk/oauth2/token
          scopes: {}

  schemas:
    Greeting:
      $ref: components/schemas/Greeting.yaml

tags:
  - name: hello
