name: apigee-release-pipeline
on:
  push

jobs:
  check-hello-world-api:
    runs-on: ubuntu-latest
    env: # Set the secret as an environment variable
      proxygen_private_key: ${{ secrets.HELLO_WORLD_PROXYGEN_PRIVATE_KEY }}
      proxygen_client_id: ${{ secrets.HELLO_WORLD_PROXYGEN_CLIENT_ID }}
    steps:
      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip 

      - name: Install poetry
        run: pip install poetry

      #- name: Install python depenancies 
      #  run: poetry install 
      
      - name: Cache poetry packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}      

      - name: Install python depenancies 
        run: |
          cd paas_client
          poetry install  

      - name: test auth
        run: echo $(poetry run python paas_client/oauth_usage_example.py "$proxygen_private_key" "$proxygen_client_id")
