name: apigee-release-pipeline
on:
  push

jobs:
  build: 
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Update apt repositories
      run: sudo apt update

    - name: Install Java and Node
      run: sudo apt-get install --yes default-jre default-jdk nodejs

    - name: Upgrade python packaging tools
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install poetry
      run: pip install poetry    
  check-hello-world-api:
    runs-on: ubuntu-latest
    env: # Set the secret as an environment variable
      proxygen_private_key: ${{ secrets.HELLO_WORLD_PROXYGEN_PRIVATE_KEY }}
      proxygen_client_id: ${{ secrets.HELLO_WORLD_PROXYGEN_CLIENT_ID }}
    steps:
      - name: test auth
        run: echo $(poetry run python paas_client/oauth_usage_example.py "$proxygen_private_key" "$proxygen_client_id")
